/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_falconcomputing_genomics_NativeLibraryLoader */

#ifndef _Included_com_falconcomputing_genomics_NativeLibraryLoader
#define _Included_com_falconcomputing_genomics_NativeLibraryLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_falconcomputing_genomics_NativeLibraryLoader
 * Method:    license_verify
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_falconcomputing_genomics_NativeLibraryLoader_license_1verify
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
