/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine */

#ifndef _Included_com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine
#define _Included_com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine
#ifdef __cplusplus
extern "C" {
#endif
#undef com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine_minBaseQual
#define com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine_minBaseQual 4L
/*
 * Class:     com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine
 * Method:    initNative
 * Signature: (III[IBIIII)V
 */
JNIEXPORT void JNICALL Java_com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine_initNative__III_3IBIIII
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jbyte, jint, jint, jint, jint);

/*
 * Class:     com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine
 * Method:    initNative
 * Signature: (I[Lorg/broadinstitute/gatk/engine/recalibration/covariates/Covariate;[B[BZIDZBIIII)V
 */
JNIEXPORT void JNICALL Java_com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine_initNative__I_3Lorg_broadinstitute_hellbender_utils_recalibration_covariates_Covariate_2_3B_3BZIDZBIIII
  (JNIEnv *, jclass, jint, jobjectArray, jbyteArray, jbyteArray, jboolean, jint, jdouble, jboolean, jbyte, jint, jint, jint, jint);

/*
 * Class:     com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine
 * Method:    setTableNative
 * Signature: (JDD[II)V
 */
JNIEXPORT void JNICALL Java_com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine_setTableNative
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jintArray, jint);


//TODO: maually change header file by Peipei
JNIEXPORT void JNICALL Java_com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine_bqsrInitReadGroupNative
(JNIEnv *, jobject, jstring readGroupId);

/*
 * Class:     com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine
 * Method:    computeContextCovariatesNative
 * Signature: ([B[BZ)[I
 */
JNIEXPORT jintArray JNICALL Java_com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine_computeContextCovariatesNative
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jboolean);

/*
 * Class:     com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine
 * Method:    computeCycleCovariatesNative
 * Signature: (IIZZZ)[I
 */
JNIEXPORT jintArray JNICALL Java_com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine_computeCycleCovariatesNative
  (JNIEnv *, jobject, jint, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine
 * Method:    computeCovariatesNative
 * Signature: ([B[B[B[BLjava/lang/String;ZZZI)[I
 */
JNIEXPORT jintArray JNICALL Java_com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine_computeCovariatesNative
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jstring, jboolean, jboolean, jboolean, jint);

/*
 * Class:     com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine
 * Method:    calculateBAQArrayNative
 * Signature: ([B[B[B[B[II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine_calculateBAQArrayNative
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jintArray, jint);

/*
 * Class:     com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine
 * Method:    calculateErrorsNative
 * Signature: ([B[B[B[B[B[I[BZZI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine_calculateErrorsNative
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jintArray, jbyteArray, jboolean, jboolean, jint);

/*
 * Class:     com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine
 * Method:    updateTableNative
 * Signature: ([B[B[B[B[B[B[B[I[BLjava/lang/String;ZZZZII[Z)I
 */
JNIEXPORT jint JNICALL Java_com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine_updateTableNative
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jintArray, jbyteArray, jstring, jboolean, jboolean, jboolean, jboolean, jint, jint, jbooleanArray);

// updateNativeSkipIndel
JNIEXPORT jint JNICALL Java_com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine_updateTableSkipIndelNative
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jintArray, jbyteArray, jstring, jboolean, jboolean, jboolean, jboolean, jint, jint, jbooleanArray);


/*
 * Class:     com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine
 * Method:    getTableNative
 * Signature: ()[Lcom/falconcomputing/genomics/bqsr/FalconRecalibrationEngine/RecalDatumTable;
 */
JNIEXPORT jobjectArray JNICALL Java_com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine_getTableNative
  (JNIEnv *, jobject);

/*
 * Class:     com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine
 * Method:    updateReadGroupCovariatesNative
 * Signature: (Lorg/broadinstitute/gatk/engine/recalibration/covariates/ReadGroupCovariate;)V
 */
JNIEXPORT void JNICALL Java_com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine_updateReadGroupCovariatesNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine
 * Method:    putRecalDatumNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine_putRecalDatumNative
  (JNIEnv *, jobject);

/*
 * Class:     com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine
 * Method:    recalibrateNative
 * Signature: ([B[B[B[BLjava/lang/String;ZZZI)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine_recalibrateNative
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jstring, jboolean, jboolean, jboolean, jint);

/*
 * Class:     com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine
 * Method:    log10QempPriorNative
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine_log10QempPriorNative
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine
 * Method:    log10QempLikelihoodNative
 * Signature: (DJJ)D
 */
JNIEXPORT jdouble JNICALL Java_com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine_log10QempLikelihoodNative
  (JNIEnv *, jobject, jdouble, jlong, jlong);

/*
 * Class:     com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine
 * Method:    bayesianEstimateOfEmpiricalQualityNative
 * Signature: (JJD)D
 */
JNIEXPORT jdouble JNICALL Java_com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine_bayesianEstimateOfEmpiricalQualityNative
  (JNIEnv *, jobject, jlong, jlong, jdouble);

/*
 * Class:     com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine
 * Method:    finalizeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine_finalizeNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine_RecalDatumTable */

#ifndef _Included_com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine_RecalDatumTable
#define _Included_com_falconcomputing_genomics_bqsr_FalconRecalibrationEngine_RecalDatumTable
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
