/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_falconcomputing_genomics_haplotypecaller_FalconSWPairwiseAlignment */

#ifndef _Included_com_falconcomputing_genomics_haplotypecaller_FalconSWPairwiseAlignment
#define _Included_com_falconcomputing_genomics_haplotypecaller_FalconSWPairwiseAlignment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_falconcomputing_genomics_haplotypecaller_FalconSWPairwiseAlignment
 * Method:    init_native
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_falconcomputing_genomics_haplotypecaller_FalconSWPairwiseAlignment_init_1native
  (JNIEnv *, jobject);

/*
 * Class:     com_falconcomputing_genomics_haplotypecaller_FalconSWPairwiseAlignment
 * Method:    align_native
 * Signature: ([B[BIIIIIZ)Lcom/falconcomputing/genomics/haplotypecaller/FalconSWPairwiseAlignment/results_native;
 */
JNIEXPORT jobject JNICALL Java_com_falconcomputing_genomics_haplotypecaller_FalconSWPairwiseAlignment_align_1native
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint, jint, jint, jint, jboolean);

/*
 * Class:     com_falconcomputing_genomics_haplotypecaller_FalconSWPairwiseAlignment
 * Method:    done_native
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_falconcomputing_genomics_haplotypecaller_FalconSWPairwiseAlignment_done_1native
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_falconcomputing_genomics_haplotypecaller_FalconSWPairwiseAlignment_results_native */

#ifndef _Included_com_falconcomputing_genomics_haplotypecaller_FalconSWPairwiseAlignment_results_native
#define _Included_com_falconcomputing_genomics_haplotypecaller_FalconSWPairwiseAlignment_results_native
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
