/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_falconcomputing_genomics_haplotypecaller_FalconPairhmm */

#ifndef _Included_com_falconcomputing_genomics_haplotypecaller_FalconPairhmm
#define _Included_com_falconcomputing_genomics_haplotypecaller_FalconPairhmm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_falconcomputing_genomics_haplotypecaller_FalconPairhmm
 * Method:    initNative
 * Signature: (Ljava/lang/Class;Ljava/lang/Class;ZIZ)V
 */
JNIEXPORT void JNICALL Java_com_falconcomputing_genomics_haplotypecaller_FalconPairhmm_initNative
  (JNIEnv *, jclass, jclass, jclass, jboolean, jint, jboolean);

/*
 * Class:     com_falconcomputing_genomics_haplotypecaller_FalconPairhmm
 * Method:    computeLikelihoodsNative
 * Signature: ([Ljava/lang/Object;[Ljava/lang/Object;[D)V
 */
JNIEXPORT void JNICALL Java_com_falconcomputing_genomics_haplotypecaller_FalconPairhmm_computeLikelihoodsNative
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jdoubleArray);

/*
 * Class:     com_falconcomputing_genomics_haplotypecaller_FalconPairhmm
 * Method:    doneNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_falconcomputing_genomics_haplotypecaller_FalconPairhmm_doneNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
