/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_falconcomputing_genomics_haplotypecaller_FalconSmithWaterman */

#ifndef _Included_com_falconcomputing_genomics_haplotypecaller_FalconSmithWaterman
#define _Included_com_falconcomputing_genomics_haplotypecaller_FalconSmithWaterman
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_falconcomputing_genomics_haplotypecaller_FalconSmithWaterman
 * Method:    init_native
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_falconcomputing_genomics_haplotypecaller_FalconSmithWaterman_init_1native
  (JNIEnv *, jobject);

/*
 * Class:     com_falconcomputing_genomics_haplotypecaller_FalconSmithWaterman
 * Method:    align_native
 * Signature: ([B[BIIIIIZ)Lcom/falconcomputing/genomics/haplotypecaller/FalconSmithWaterman/FalconSWResultsNative;
 */
JNIEXPORT jobject JNICALL Java_com_falconcomputing_genomics_haplotypecaller_FalconSmithWaterman_align_1native
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint, jint, jint, jint);

/*
 * Class:     com_falconcomputing_genomics_haplotypecaller_FalconSmithWaterman
 * Method:    done_native
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_falconcomputing_genomics_haplotypecaller_FalconSmithWaterman_done_1native
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_falconcomputing_genomics_haplotypecaller_FalconSmithWaterman_FalconSWResultsNative */

#ifndef _Included_com_falconcomputing_genomics_haplotypecaller_FalconSmithWaterman_FalconSWResultsNative
#define _Included_com_falconcomputing_genomics_haplotypecaller_FalconSmithWaterman_FalconSWResultsNative
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
